-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

---- Fix conceallevel for json & help files
-- vim.api.nvim_create_autocmd({ "FileType" }, {
--   pattern = { "json", "jsonc" },
--   callback = function()
--     vim.wo.spell = false
--     vim.wo.conceallevel = 0
--   end,
-- })

-- show cursor line only in active window
-- vim.api.nvim_create_autocmd({ "InsertLeave", "WinEnter" }, {
--   callback = function()
--     local ok, cl = pcall(vim.api.nvim_win_get_var, 0, "auto-cursorline")
--     if ok and cl then
--       vim.wo.cursorline = true
--       vim.api.nvim_win_del_var(0, "auto-cursorline")
--     end
--   end,
-- })
-- vim.api.nvim_create_autocmd({ "InsertEnter", "WinLeave" }, {
--   callback = function()
--     local cl = vim.wo.cursorline
--     if cl then
--       vim.api.nvim_win_set_var(0, "auto-cursorline", cl)
--       vim.wo.cursorline = false
--     end
--   end,
-- })

-- create directories when needed, when saving a file
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   group = vim.api.nvim_create_augroup("auto_create_dir", { clear = true }),
--   callback = function(event)
--     local file = vim.loop.fs_realpath(event.match) or event.match
--
--     vim.fn.mkdir(vim.fn.fnamemodify(file, ":p:h"), "p")
--     local backup = vim.fn.fnamemodify(file, ":p:~:h")
--     backup = backup:gsub("[/\\]", "%%")
--     vim.go.backupext = backup
--   end,
-- })

-- -- Disable skip_unbalanced for Clojure files, enable for others
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "*",
--   callback = function(ev)
--     local skip_unbalanced = true
--     if vim.bo[ev.buf].filetype == "clojure" then
--       skip_unbalanced = false
--     end
--     local config = require("mini.pairs").config
--     config.skip_unbalanced = skip_unbalanced
--     require("mini.pairs").setup(config)
--   end,
-- })

-- vim.api.nvim_create_autocmd("BufWritePost", {
--   group = vim.api.nvim_create_augroup("md_calcdown", { clear = true }),
--   pattern = "*.md",
--   callback = function(event)
--     local file = vim.loop.fs_realpath(event.match) or event.match
--     local cmd = "!calcdown -i " .. file .. " --replace"
--     vim.api.nvim_command(cmd)
--   end,
-- })
